name: Release automatically
on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: [ksu_merge_update]
permissions:
      contents: write
jobs:
  update-ksu:
    uses: ./.github/workflows/ksu_update.yml
  build-pixelos:
    needs:
      - update-ksu
    uses: ./.github/workflows/build_pixelos.yml
  build-oos:
    needs:
      - update-ksu
    uses: ./.github/workflows/build_oos11.yml
  build-los:
    needs:
      - update-ksu
    uses: ./.github/workflows/build_los.yml
  release:
    needs:
      - build-pixelos
      - build-oos
      - build-los
      - update-ksu
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Zip AnyKernel3
        run: |
          for dir in AnyKernel_*; do
            if [ -d "$dir" ]; then
              echo "----- Zip $dir -----"
              (cd $dir && zip -r9 "$dir".zip ./* -x .git .gitignore ./*.zip && mv *.zip ..)
            fi
          done
        
      - name: Set up date
        run: echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y.%m.%d %H:%M")" >> $GITHUB_ENV

      - name: Get version from weishu's ksu
        run: |
          sudo apt install -y curl jq
          KSU_RELEASE=`curl https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r .tag_name`
          echo $KSU_RELEASE
          echo "KSU_RELEASE=$KSU_RELEASE" >> $GITHUB_ENV
          
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: KernelTarget
          name: Kernel target release (${{ env.KSU_RELEASE }})
          files: AnyKernel_*.zip
          body: |
            Build Time
            ${{ env.BUILD_TIME }}

            KernelSU Version
            ${{ env.KSU_RELEASE }}

            Type
            AUTOMATICALLY
