name: Update submodules
on:
  workflow_dispatch:
  workflow_call:
jobs: 
  los-update:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps: 
      - name: Checkout Kernel
        uses: actions/checkout@v3
        with:
          repository: Grill-Laux/kernel_oneplus_sdm845
          ref: los/lineage-21.0
      - name: Update submodule(s)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git submodule update --init --remote --recursive -f
          git commit -asm "KernelSU: Merge to newest"
          git push
          
  oos-update:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps: 
      - name: Checkout Kernel
        uses: actions/checkout@v3
        with:
          repository: Grill-Laux/kernel_oneplus_sdm845
          ref: oos/11.0
      - name: Update submodule(s)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git submodule update --init --remote --recursive -f
          git commit -asm "KernelSU: Merge to newest"
          git push         
